### ISSUE TITLE
Hello, I'm currently working on this, how can i get the raw frontend file from you...

### ISSUE THREAD

**Issue by Abeeujah** [steinily/Nasa-Project#1]
Hello, I'm currently working on this, how can i get the raw frontend file from you...

**Comment by steinily** [comment]
I dont finished yet the course, for this project, so  all the files what can i offer is available to clone

**Comment by Abeeujah** [comment]
You did not edit anything in the frontend of the nasa project?

**Comment by Abeeujah** [comment]
I'm trying to restart from scratch... I want to code along with the tutor
